import { SyntaxNode, Identifier, SyntaxKind, Graph, EdgeStatement, EdgeRhs, SourceFile, SubGraphStatement, NodeId, AttributeStatement } from "./types";
export declare function checkSourceFile(file: SourceFile): void;
export declare function findNodeAtOffset(root: SyntaxNode, offset: number): SyntaxNode | undefined;
export declare function getAllowedEdgeOperation(graph: Graph): SyntaxKind.DirectedEdgeOp | SyntaxKind.UndirectedEdgeOp;
export declare function findAllEdges(node: SyntaxNode): EdgeRhs[];
export declare function isAttrStatement(node: SyntaxNode): node is AttributeStatement;
export declare function isEdgeStatement(node: SyntaxNode): node is EdgeStatement;
export declare function isSubGraphStatement(node: SyntaxNode): node is SubGraphStatement;
export declare function isNodeId(node: SyntaxNode): node is NodeId;
export declare function edgeStatementHasAttributes(es: EdgeStatement): boolean;
export declare function getIdentifierText(n: Identifier): string | undefined;
