name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x, 25.x]

    steps:
    - uses: actions/checkout@v5
      with:
        show-progress: false

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - run: npm ci
    - run: npm run ci
    - run: npm run build
    - run: npm test
      env:
        CI: true
